### ISSUE TITLE
Expose service visibility

### ISSUE THREAD

**Issue by elonmir** [DZunke/FeatureFlagsBundle#11]
> User Deprecated: The "dz.feature_flags.toggle" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

If I understand the documentation correclty the service *dz.feature_flags.toggle* needs to be public.
 I added a PR to make the change.

**Comment by DZunke** [comment]
👍 Thanks Elonmir. You are absolutely correct!

**Comment by DZunke** [comment]
Fixed with https://github.com/DZunke/FeatureFlagsBundle/commit/80621147631a3a787c281008012e672a81fdbea0
