### ISSUE TITLE
Question: Any plans for supporting Symfony 4.*?

### ISSUE THREAD

**Issue by Mahmoudz** [DZunke/FeatureFlagsBundle#13]
Hi @DZunke, thanks for this useful package.

I'm in the process of upgrading a legacy codebase from Symfony 3.4 to 4.1. 
And I was wondering if you have plans for supporting Sy4 anytime soon "like within 48 hours"!?
It's ok if you don't have time for it now, I may get someone or myself to handle it and contribute back, if you don't mind.

Best,

**Comment by DZunke** [comment]
Hey @Mahmoudz,

hopefully version 3.0 will help you. Updated some stuff and added support vor symfony 4.x but not for symfony flex. 

Greets
