### ISSUE TITLE
Symfony 2.3 is not yet at EOL

### ISSUE THREAD

**Issue by alexwilson** [DZunke/FeatureFlagsBundle#4]
Hey,

In a8beb81fa3134113cff8370d29a3d5c406cb5ae7 Symfony 2.3 has been removed from the composer dependency range, with the justification that it is EOL.  According to the Symfony roadmap, it is not EOL May 2017, and will still be seeing security patches until this date.

Could you please reverse the change to `composer.json` until next May (under the proviso that there not be support for incompatibilities!), as alongside #3 (pretty please!) there are a bunch of features in v1.1.0 which greatly increase what is possible with this bundle in "legacy" Symfony applications even when support for those versions is finally dropped in this bundle.

Happy to PR if you haven't the time!

Cheers,
Alex

**Comment by DZunke** [comment]
Hi,

 i could understand your problem. Sorry, was my fault to break compability in a minor version. I will try to re-enable symfony 2.3 for the 1.x-branch. The Commit Message was a bit confusing, ment to disable php 5.4 due to EOL. 

Will have a quick check if all is working with symfony 2.3 :smile:

**Comment by DZunke** [comment]
Hey,

1.x has re-enabled symfony 2.3 support. I'd created 2.x-branch for the removal of symfony 2.3 support. When #3 is merged into master i will create a release 1.2 with this change. Hope it works for you this way!

**Comment by alexwilson** [comment]
That sounds ideal, thanks!

**Comment by DZunke** [comment]
Version 1.2.1 with Symfony 2.3 Support, dropped Symfony 3 Support, is now released. Added a note to the readme to use >=2.0 to get Symfony 3 Support back.  :smile_cat: 

I think the Issue could be closed with this work done!

**Comment by alexwilson** [comment]
Awesome!  Huge thanks for this!
